In [1]:
import torch
from torch import nn
net = nn.Sequential(nn.LazyLinear(256),nn.ReLU(),nn.Linear(256,10))
print(net)

F:\programData\conda\env\ChatGLM2-6B\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
F:\programData\conda\env\ChatGLM2-6B\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
F:\programData\conda\env\ChatGLM2-6B\lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


Sequential(
  (0): LazyLinear(in_features=0, out_features=256, bias=True)
  (1): ReLU()
  (2): Linear(in_features=256, out_features=10, bias=True)
)


F:\programData\conda\env\ChatGLM2-6B\lib\site-packages\torch\nn\modules\lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [2]:
[net[i].state_dict() for i in range(len(net))]

[OrderedDict([('weight', <UninitializedParameter>),
              ('bias', <UninitializedParameter>)]),
 OrderedDict(),
 OrderedDict([('weight',
               tensor([[-0.0023, -0.0566,  0.0407,  ..., -0.0563,  0.0205, -0.0145],
                       [ 0.0479, -0.0451, -0.0145,  ...,  0.0516, -0.0037,  0.0088],
                       [ 0.0125, -0.0382,  0.0600,  ..., -0.0138,  0.0567, -0.0440],
                       ...,
                       [-0.0217,  0.0002, -0.0163,  ...,  0.0499, -0.0522,  0.0560],
                       [ 0.0231,  0.0612,  0.0597,  ..., -0.0445, -0.0031,  0.0096],
                       [ 0.0129, -0.0038,  0.0371,  ...,  0.0274,  0.0079,  0.0511]])),
              ('bias',
               tensor([ 0.0181,  0.0042, -0.0021,  0.0345, -0.0336,  0.0587,  0.0451,  0.0247,
                        0.0251,  0.0081]))])]

In [4]:
low = torch.finfo(torch.float32).min/10
high = torch.finfo(torch.float32).max/10

x = torch.zeros([2,20],dtype=torch.float32).uniform_(low,high)
net(x)

tensor([[-1.5022e+36, -6.7023e+36,  5.8205e+36, -2.8856e+36,  1.8594e+35,
          3.8865e+36, -9.3596e+36,  1.1447e+36,  4.5275e+36,  8.6368e+35],
        [-8.0457e+36, -1.5462e+37,  3.3207e+36,  2.6372e+36, -2.0282e+36,
          4.6078e+36, -3.1301e+36,  7.8631e+36, -8.9157e+34, -1.8980e+36]],
       grad_fn=<AddmmBackward0>)

In [5]:
print(net)

Sequential(
  (0): Linear(in_features=20, out_features=256, bias=True)
  (1): ReLU()
  (2): Linear(in_features=256, out_features=10, bias=True)
)
