In [2]:
#6.4.1. 多输入通道
import torch
from d2l import torch as d2l

def corr2d_multi_in(X,K):
    return sum(d2l.corr2d(x,k) for x,k in zip(X,K))

F:\programData\conda\env\ChatGLM2-6B\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
F:\programData\conda\env\ChatGLM2-6B\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
F:\programData\conda\env\ChatGLM2-6B\lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [3]:
X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
               [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])

corr2d_multi_in(X,K)

tensor([[ 56.,  72.],
        [104., 120.]])

In [5]:
X.shape

torch.Size([2, 3, 3])

In [7]:
K.shape

torch.Size([2, 2, 2])

In [8]:
def corr2d_multi_in_out(X,K):
    return torch.stack([corr2d_multi_in(X,k) for k in K],0)

K = torch.stack((K,K+1,K+2),0)
K.shape

torch.Size([3, 2, 2, 2])

In [9]:
corr2d_multi_in_out(X,K)

tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])

In [14]:
#6.4.3.  1X1卷积层
def corred_multi_in_out_1x1(X,K):
    c_i,h,w = X.shape
    c_o = K.shape[0]
    X = X.reshape((c_i,h*w))
    K = K.reshape((c_o,c_i))
    Y = torch.matmul(K,X)
    return  Y.reshape((c_o,h,w))

In [20]:
X = torch.normal(0,1,(3,3,3))
K = torch.normal(0,1,(2,3,1,1))

Y1 = corred_multi_in_out_1x1(X,K)
Y2 = corr2d_multi_in_out(X,K)
Y1,Y1.shape,Y2,Y2.shape

(tensor([[[-0.3586, -1.5871,  0.1131],
          [-2.8219, -0.1497, -1.4170],
          [ 1.9417, -6.4065, -4.9319]],
 
         [[ 0.5200, -0.4373, -0.0845],
          [-0.3868,  0.8042, -1.2372],
          [ 0.4240,  1.0396,  0.6554]]]),
 torch.Size([2, 3, 3]),
 tensor([[[-0.3586, -1.5871,  0.1131],
          [-2.8219, -0.1497, -1.4170],
          [ 1.9417, -6.4065, -4.9319]],
 
         [[ 0.5200, -0.4373, -0.0845],
          [-0.3868,  0.8042, -1.2372],
          [ 0.4240,  1.0396,  0.6554]]]),
 torch.Size([2, 3, 3]))