In [1]:
#2.6 概率

In [2]:
#2.6.1. 基本概率论
#大数定律（law of large numbers）告诉我们：
#随着投掷次数的增加，这个估计值会越来越接近真实的潜在概率
%matplotlib inline
import torch
from torch.distributions import multinomial
from d2l import torch as d2l

F:\programData\conda\env\ChatGLM2-6B\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
F:\programData\conda\env\ChatGLM2-6B\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
F:\programData\conda\env\ChatGLM2-6B\lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [6]:
fair_probs = torch.ones([6]) / 6
multinomial.Multinomial(1,fair_probs).sample()

tensor([0., 0., 0., 0., 1., 0.])

In [7]:
multinomial.Multinomial(10,fair_probs).sample()

tensor([2., 4., 1., 1., 2., 0.])

In [8]:
# 将结果存储为32位浮点数以进行除法
counts = multinomial.Multinomial(1000,fair_probs).sample()
counts /1000

tensor([0.1780, 0.1750, 0.1690, 0.1500, 0.1600, 0.1680])

In [10]:
#进行500组实验，每组抽取10个样本
counts = multinomial.Multinomial(10,fair_probs).sample((500,))
cum_counts = counts.cumsum(dim=0)
estimates = cum_counts/cum_counts.sum(dim=1,keepdims=True)
estimates

tensor([[0.3000, 0.3000, 0.1000, 0.0000, 0.2000, 0.1000],
        [0.2000, 0.1500, 0.2000, 0.1500, 0.2500, 0.0500],
        [0.2000, 0.2000, 0.1667, 0.1333, 0.1667, 0.1333],
        ...,
        [0.1622, 0.1620, 0.1669, 0.1647, 0.1703, 0.1739],
        [0.1619, 0.1625, 0.1665, 0.1645, 0.1707, 0.1737],
        [0.1618, 0.1626, 0.1668, 0.1642, 0.1710, 0.1736]])