In [ ]:
#2.3 线性代数

In [2]:
#2.3.1. 标量
#标量由只有一个元素的张量表示
import  torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y,x * y, x / y,x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [3]:
# 2.3.2 向量
# 向量可以被视为标量值组成的列表。
# 列向量是向量的默认方向
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
#通过张量的索引来访问任一元素
x[3]

tensor(3)

In [5]:
# 2.3.2.1. 长度、维度和形状
len(x)

4

In [6]:
x.shape

torch.Size([4])

In [7]:
#2.3.3. 矩阵
#向量将标量从零阶推广到一阶，矩阵将向量从一阶推广到二阶
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
#矩阵转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
# 2.3.4. 张量
#张量是描述具有任意数量轴的n维数组的通用方法。 
#例如，向量是一阶张量，矩阵是二阶张量
x = torch.arange(24).reshape(2,3,4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [10]:
# 2.3.5. 张量算法的基本性质
# 张量加法
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [11]:
# 张量乘法
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [12]:
#将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。
a = 2
X = torch.arange(24).reshape((2,3,4))
a + X, a * X


(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]))

In [13]:
#2.3.6. 降维
# 求和
x = torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [14]:
A,A.shape, A.sum()

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]),
 tensor(190.))

In [15]:
# 指定维度
# 指定了维度0，那么维度0上所有的值相加，最终结果应该维度1的大小
A_sum_axis0 = A.sum(axis= 0)
A_sum_axis0 ,A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [16]:
# 指定了维度1，那么维度1上所有的值相加，最终结果应该维度0的大小
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1,A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [17]:
# 沿着行和列对矩阵求和，等价于对矩阵的所有元素进行求和
A.sum(axis=[0,1]) # 结果和A.sum()相同

tensor(190.)

In [18]:
#求平均值
A.mean()

tensor(9.5000)

In [19]:
#平均值的函数也可以沿指定轴降低张量的维度
A.mean(axis=0)

tensor([ 8.,  9., 10., 11.])

In [20]:
#2.3.6.1. 非降维求和
# 计算总和或均值时保持轴数不变
sum_A =  A.sum(axis= 1,keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [21]:
# Sum_A在对每行进行求和后仍保持两个轴，我们可以通过广播将A除以sum_A
A /sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [22]:
#如果我们想沿某个轴计算A元素的累积总和， 比如axis=0（按行计算）
#可以调用cumsum函数。 此函数不会沿任何轴降低输入张量的维度
A,A.cumsum(axis=0)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]))

In [ ]:
#2.3.7. 点积
y = torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

In [ ]:
# 2.3.8 矩阵-向量积
A.shape,x.shape,torch.mv(A,x)

In [ ]:
# 2.3.9 矩阵-矩阵乘法
B = torch.ones(4,3)
torch.mm(A,B)

In [ ]:
# 2.3.10 范数
#L2 范数
u = torch.tensor([3.0,-4.0])
torch.

In [25]:
# 2.3.8 矩阵-向量积
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [26]:
# 2.3.9 矩阵-矩阵乘法
B = torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [ ]:
# 2.3.10 范数
#L2 范数
u = torch.tensor([3.0,-4.0])
torch.